layouts:
  - name: Home Page
    view: index
  - name: Página com Barra Lateral à Direita
    view: page
  - name: Página com Barra Lateral à Esquerda
    view: page-left
  - name: Página sem Barra Lateral
    view: page-inteira

comments_default:
  - name: Padrão
    file: comments_default
  - name: Visualização Rotativa
    file: comments_rotate

block_types:
  - name: Blog
    file: lista-blog
    group: Exemplos de listas
  - name: 1 Coluna
    file: lista-grade-1-coluna
    group: Exemplos de listas
  - name: 2 Colunas
    file: lista-grade-2-colunas
    group: Exemplos de listas
  - name: 3 Colunas
    file: lista-grade-3-colunas
    group: Exemplos de listas
  - name: Compacta com Hora
    file: lista-compacta-com-hora
    group: Exemplos de listas
  - name: Compacta com Data
    file: lista-compacta-com-data
    group: Exemplos de listas
  - name: Mini Compacta com Hora
    file: lista-mini-compacta-com-hora
    group: Exemplos de listas
  - name: Mini Compacta com Data
    file: lista-mini-compacta-com-data
    group: Exemplos de listas
  - name: 3 Colunas (Página Inteira)
    file: lista-grade-3-colunas-full
    group: Exemplos de listas
  - name: 4 Colunas (Página Inteira)
    file: lista-grade-4-colunas-full
    group: Exemplos de listas
  - name: Vertical Título Grande
    file: destaque-vertical-grande
    group: Blocos de destaques
  - name: Vertical Título Médio
    file: destaque-vertical-medio
    group: Blocos de destaques
  - name: Vertical Título Pequeno
    file: destaque-vertical-pequeno
    group: Blocos de destaques
  - name: Horizontal Título Grande
    file: destaque-horizontal-grande
    group: Blocos de destaques
  - name: Horizontal Título Médio
    file: destaque-horizontal-medio
    group: Blocos de destaques
  - name: Quadrado com Categoria e Título
    file: destaque-quadrado-categoria-titulo
    group: Blocos de destaques
  - name: Quadrado com Foto do Autor
    file: destaque-quadrado-foto-autor
    group: Blocos de destaques
  - name: Título Grande
    file: destaque-texto-grande
    group: Blocos de destaques
  - name: Título Médio
    file: destaque-texto-medio
    group: Blocos de destaques
  - name: Título Pequeno
    file: destaque-texto-pequeno
    group: Blocos de destaques
  - name: Data e Título
    file: destaque-simples-com-data
    group: Blocos de destaques
  - name: Categoria e Título
    file: destaque-simples-com-categoria
    group: Blocos de destaques
  - name: Marcador e Título
    file: destaque-simples-com-marcador
    group: Blocos de destaques
  - name: Destaque Scroll Horizontal
    file: destaque-scroll-horizontal
    group: Blocos de destaques
  - name: Destaque Scroll Vertical
    file: destaque-scroll-vertical
    group: Blocos de destaques
  - name: Destaque Rotativo Padrão
    file: destaque-rotativo-padrao
    group: Blocos de destaques
  - name: Destaque Rotativo Wide
    file: destaque-rotativo-wide
    group: Blocos de destaques

box_types:
  - name: Caixa Padrão
    file: cx-caixa-padrao
  - name: Caixa Padrão com borda
    file: cx-caixa-padrao-com-borda

form_types:
  - name: Padrão
    file: form-padrao